/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestRecombination.java
 *
 * Created on 6/Nov/2010, 10:41:15
 */
package GUI.research;

import GUI.Graphics.TSP_Graphics;
import genetic.population.Population;
import genetic.population.SimplePopulation;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import operator.mutation.Mutation;
import operator.recombination.Recombination;
import problem.Individual;
import problem.permutation.TSP.AbstractTSP;
import utils.DynamicLoad;
import utils.GAJarFile;

/**
 *
 * @author manso
 */
public class ResearchXpermut extends javax.swing.JFrame {

    Population parents;
    Population childrens;
    String strCROSSOVER = "operator.recombination.permutation";
    String strMUTATION = "operator.mutation.permutation";
    String strPROBLEM = "problem.permutation.TSP";

    /**
     * Creates new form TestRecombination
     */
    public ResearchXpermut() {
        initComponents();
        loadJar(strCROSSOVER, lstCrossover);
        loadJar(strMUTATION, lstMutation);
        loadJar(strPROBLEM, lstProblems);
        btCreatePopulationActionPerformed(null);

    }

    private void loadJar(String model, JList lst) {
        ArrayList<String> rec = GAJarFile.getClassName(model);
        DefaultListModel modelL = new DefaultListModel();
        //select the default
        int indexOfDefault = 0;
        for (int i = 0; i < rec.size(); i++) {
            modelL.add(i, rec.get(i));
            if (rec.get(i).equalsIgnoreCase("default")) {
                indexOfDefault = i;
            }
        }
        lst.setModel(modelL);
        //set the default selected
        lst.setSelectedIndex(indexOfDefault);
        lst.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        pnParents = new javax.swing.JPanel();
        pnChildrens = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProblems = new javax.swing.JList();
        txtProblemParams = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSizeOfPopulation = new javax.swing.JTextField();
        sldSizeOfPopulation = new javax.swing.JSlider();
        btCreatePopulation = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCrossover = new javax.swing.JList();
        txtCRossoverPArams = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btRunCrossover = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMutation = new javax.swing.JList();
        txtParamMutation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btRunMutation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.setPreferredSize(new java.awt.Dimension(900, 900));
        panel.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        pnParents.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnParentsLayout = new javax.swing.GroupLayout(pnParents);
        pnParents.setLayout(pnParentsLayout);
        pnParentsLayout.setHorizontalGroup(
            pnParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        pnParentsLayout.setVerticalGroup(
            pnParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        panel.add(pnParents);

        pnChildrens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnChildrensLayout = new javax.swing.GroupLayout(pnChildrens);
        pnChildrens.setLayout(pnChildrensLayout);
        pnChildrensLayout.setHorizontalGroup(
            pnChildrensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        pnChildrensLayout.setVerticalGroup(
            pnChildrensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        panel.add(pnChildrens);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 800));
        jPanel4.setLayout(new java.awt.GridLayout(4, 0, 1, 1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lstProblems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProblemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProblems);

        txtProblemParams.setText(" ");

        jButton4.setText("params");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProblemParams, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtProblemParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Size of Population");

        txtSizeOfPopulation.setEditable(false);
        txtSizeOfPopulation.setText("2");

        sldSizeOfPopulation.setMaximum(10);
        sldSizeOfPopulation.setMinimum(2);
        sldSizeOfPopulation.setValue(2);
        sldSizeOfPopulation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSizeOfPopulationStateChanged(evt);
            }
        });

        btCreatePopulation.setText("Create New Population");
        btCreatePopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreatePopulationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btCreatePopulation, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSizeOfPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(sldSizeOfPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSizeOfPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldSizeOfPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCreatePopulation, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Crossover");

        lstCrossover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCrossoverMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCrossover);

        txtCRossoverPArams.setText("1");

        jLabel3.setText("parameters");

        btRunCrossover.setText("run");
        btRunCrossover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunCrossoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCRossoverPArams, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addComponent(btRunCrossover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCRossoverPArams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRunCrossover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Mutation");

        lstMutation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMutationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstMutation);

        txtParamMutation.setText("1");

        jLabel5.setText("parameters");

        btRunMutation.setText("run");
        btRunMutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunMutationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtParamMutation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRunMutation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtParamMutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRunMutation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel5);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCrossoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCrossoverMouseClicked
    }//GEN-LAST:event_lstCrossoverMouseClicked

    private void sldSizeOfPopulationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSizeOfPopulationStateChanged
        txtSizeOfPopulation.setText(sldSizeOfPopulation.getValue() + "");
    }//GEN-LAST:event_sldSizeOfPopulationStateChanged

    private void lstProblemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProblemsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstProblemsMouseClicked

    private void lstMutationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMutationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstMutationMouseClicked

    private void drawPopulation(Population pop, JPanel panel, Color color) {
        if (pop.isEmpty()) {
            panel.getGraphics().clearRect(0, 0, panel.getWidth(), panel.getHeight());
            return;
        }
        TSP_Graphics graph = new TSP_Graphics();
        int dy = panel.getHeight() / pop.getNumGenotypes();
        int x1 = panel.getWidth();

        for (int i = 0; i < pop.getNumGenotypes(); i++) {
            graph.showTSP((AbstractTSP) pop.getGenotype(i),color, panel.getGraphics(), 0, dy * i, x1, (i + 1) * dy);
        }
    }

    private void btCreatePopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreatePopulationActionPerformed
        String problem = strPROBLEM + "." + lstProblems.getSelectedValue().toString();
        Individual template = (Individual) DynamicLoad.makeObject(problem);
        template.setParameters(txtProblemParams.getText() + "");
        parents = new SimplePopulation();
        parents.createRandomPopulation(sldSizeOfPopulation.getValue(), template);
        parents.evaluate();
        drawPopulation(parents, pnParents, Color.BLUE);
        childrens = new SimplePopulation();
        childrens.evaluate();
        drawPopulation(childrens, pnChildrens, Color.BLACK);

    }//GEN-LAST:event_btCreatePopulationActionPerformed

    private void btRunCrossoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunCrossoverActionPerformed
        String cross = strCROSSOVER + "." + lstCrossover.getSelectedValue().toString();
        Recombination operator = (Recombination) DynamicLoad.makeObject(cross);
        operator.setParameters(txtCRossoverPArams.getText() + "");
        childrens = operator.execute(parents.getClone());
        childrens.evaluate();
        drawPopulation(childrens, pnChildrens, Color.GREEN);
    }//GEN-LAST:event_btRunCrossoverActionPerformed

    private void btRunMutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunMutationActionPerformed
        String mut = strMUTATION + "." + lstMutation.getSelectedValue().toString();
        Mutation operator = (Mutation) DynamicLoad.makeObject(mut);
        operator.setParameters(txtParamMutation.getText() + "");
        childrens = operator.execute(parents.getClone());
        childrens.evaluate();
        drawPopulation(childrens, pnChildrens, Color.RED);
    }//GEN-LAST:event_btRunMutationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ResearchXpermut().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreatePopulation;
    private javax.swing.JButton btRunCrossover;
    private javax.swing.JButton btRunMutation;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstCrossover;
    private javax.swing.JList lstMutation;
    private javax.swing.JList lstProblems;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnChildrens;
    private javax.swing.JPanel pnParents;
    private javax.swing.JSlider sldSizeOfPopulation;
    private javax.swing.JTextField txtCRossoverPArams;
    private javax.swing.JTextField txtParamMutation;
    private javax.swing.JTextField txtProblemParams;
    private javax.swing.JTextField txtSizeOfPopulation;
    // End of variables declaration//GEN-END:variables
}
