/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ZULU
 */
public class MuGA_About extends javax.swing.JFrame {
    //main meno of this frame

    JFrame mainMenu;

    /**
     * Creates new form MuGA_Menu
     */
    public MuGA_About(JFrame mainMenu) {
        initComponents();
        this.mainMenu = mainMenu;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((dim.width - this.getWidth()) / 2, (dim.height - this.getHeight()) / 2, this.getWidth(), this.getHeight());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAbout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btMainMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pnAbout.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/LabMag_very_Small.png"))); // NOI18N
        pnAbout.add(jLabel4);
        jLabel4.setBounds(430, 20, 310, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/ipt.png"))); // NOI18N
        pnAbout.add(jLabel5);
        jLabel5.setBounds(10, 9, 220, 101);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Instituto Politécnico de Tomar\nQuinta do Contador - Estrada da Serra \n2300-313 Tomar - Portugal \nmanso@ipt.pt\n");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setOpaque(false);
        jTextArea1.setRequestFocusEnabled(false);
        pnAbout.add(jTextArea1);
        jTextArea1.setBounds(30, 260, 308, 80);

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jTextArea2.setText("LabMAg - Laboratório de Modelaç?o de Agentes\nUniversidade de Lisboa, Campo Grande\n1749-016 Lisboa – Portugal\nLuis.Correia@di.fc.ul.pt\n");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setOpaque(false);
        jTextArea2.setRequestFocusEnabled(false);
        pnAbout.add(jTextArea2);
        jTextArea2.setBounds(360, 250, 356, 90);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("António Manso");
        pnAbout.add(jLabel12);
        jLabel12.setBounds(30, 230, 190, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Luís Correia");
        pnAbout.add(jLabel13);
        jLabel13.setBounds(360, 220, 190, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MuGA-T - Multiset Genetic Algorithm Tool");
        pnAbout.add(jLabel14);
        jLabel14.setBounds(0, 130, 700, 70);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("A Tool to Explore  Multisets");
        pnAbout.add(jLabel16);
        jLabel16.setBounds(190, 190, 300, 22);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/fc_ul.png"))); // NOI18N
        pnAbout.add(jLabel17);
        jLabel17.setBounds(230, 0, 220, 190);

        btMainMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/home_64.png"))); // NOI18N
        btMainMenu1.setText("Main Menu");
        btMainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMainMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMainMenu1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMainMenu1ActionPerformed
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMainMenu1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMainMenu1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel pnAbout;
    // End of variables declaration//GEN-END:variables
}
