/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ZULU
 */
public class MuGA_Menu extends javax.swing.JFrame {

    /**
     * Creates new form MuGA_Menu
     */
    public MuGA_Menu() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((dim.width - this.getWidth()) / 2, (dim.height - this.getHeight()) / 2, this.getWidth(), this.getHeight());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btRun = new javax.swing.JButton();
        btExplore = new javax.swing.JButton();
        btCompare = new javax.swing.JButton();
        btResearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        btResearch1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        btRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Icons/Run_128.png"))); // NOI18N
        btRun.setText("Run");
        btRun.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });
        jPanel1.add(btRun);

        btExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Explore_128.png"))); // NOI18N
        btExplore.setText("Explore");
        btExplore.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btExplore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExplore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExploreActionPerformed(evt);
            }
        });
        jPanel1.add(btExplore);

        btCompare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Compare_128.png"))); // NOI18N
        btCompare.setText("Compare");
        btCompare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btCompare.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCompare.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompareActionPerformed(evt);
            }
        });
        jPanel1.add(btCompare);

        btResearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Research_128.png"))); // NOI18N
        btResearch.setText("Research");
        btResearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btResearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btResearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btResearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResearchActionPerformed(evt);
            }
        });
        jPanel1.add(btResearch);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MuGA-T - Multiset Genetic Algorithm Tool");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("A Tool to Explore  Multisets");

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Exit_64.png"))); // NOI18N
        btExit.setText("Exit");
        btExit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btResearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/About_64.png"))); // NOI18N
        btResearch1.setText("About");
        btResearch1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btResearch1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btResearch1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btResearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResearch1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/LabMag_very_Small.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btResearch1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExit))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btResearch1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
        RunSimpleSolver form = new RunSimpleSolver(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRunActionPerformed

    private void btExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExploreActionPerformed
        Run_MeanSolver form = new Run_MeanSolver(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btExploreActionPerformed

    private void btCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompareActionPerformed
        RunMultipleSolvers form = new RunMultipleSolvers(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCompareActionPerformed

    private void btResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResearchActionPerformed
        JOptionPane.showMessageDialog(this, "Soon!");
    }//GEN-LAST:event_btResearchActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void btResearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResearch1ActionPerformed
        MuGA_About form = new MuGA_About(this);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btResearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuGA_Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompare;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btExplore;
    private javax.swing.JButton btResearch;
    private javax.swing.JButton btResearch1;
    private javax.swing.JButton btRun;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
