/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOfStatistics.java
 *
 * Created on 1/Nov/2009, 18:07:22
 */
package GUI;


import genetic.Solver.SimpleSolver;
import java.awt.BorderLayout;
import java.util.List;
import java.util.Vector;
import statistics.Mean_Of_Solver;
import statistics.MultiPanelStatistics;

/**
 *
 * @author manso
 */
public class PanelOfStatistics extends javax.swing.JFrame {

    public MultiPanelStatistics stats = null;

    /** Creates new form PanelOfStatistics */
    public PanelOfStatistics(SimpleSolver s) {
        initComponents();
        setSolver(s);
    }
    /** Creates new form PanelOfStatistics */
    public PanelOfStatistics(Vector s) {
        initComponents();
        setSolver(s);
    }

    public void setSolver(SimpleSolver s) {
        Vector v = new Vector();
        v.add(s);
       setSolver(v);

    }

   

    public void setSolver(List solver) {
        if (solver == null || solver.isEmpty()) {
            return;
        }
        int size = solver.size();
        if (solver.get(0) instanceof Mean_Of_Solver) {
            size = ((Mean_Of_Solver) solver.get(0)).NUMBER_OF_POPULATIONS;
        }
        setTitle("statistical average of " + size + " solvers of " + ((SimpleSolver) solver.get(0)).getTemplate().getName());
        stats = new MultiPanelStatistics();
        stats.setSolvers(solver);
        this.setLayout(new BorderLayout());
        this.getContentPane().removeAll();
        this.getContentPane().add(stats.getTabs(), BorderLayout.CENTER);
        this.pack();
        this.repaint();
    }
    
    public void saveStatisticsImages(String path){
        if( stats != null)
            stats.saveStatisticsImages(path);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
