/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOfPopulation.java
 *
 * Created on 16/Out/2009, 15:57:37
 */
package GUI;

import GUI.Graphics.DisplayBits;
import GUI.Graphics.DisplayPhenotype;
import genetic.Solver.SimpleSolver;
import genetic.Solver.GA;
import genetic.population.Population;
import genetic.population.SimplePopulation;
import problem.Default;

/**
 *
 * @author manso
 */
public class PanelOfPopulation extends javax.swing.JFrame {

    private Population pop = new SimplePopulation();
    private SimpleSolver solver = new GA();
    GUI.Graphics.DisplayPopulation displayBits = new DisplayBits();
    //GUI.Graphics.DisplayPopulation displayBitsPop = new DisplayBitsPopulation();
    GUI.Graphics.DisplayPhenotype displayPheno = new DisplayPhenotype();
    boolean is_Shown_In_The_Screen = true;

    // GUI.Graphics.Display3DFuncDynamic display3DDynamic = new Display3DFuncDynamic();
    /**
     * Creates new form PanelOfPopulation
     */
    public PanelOfPopulation() {
        initComponents();
        tbGraphGenotype.add(displayBits);
        //  tbGraphGenotypePop.add(displayBitsPop);
        tbGraphPhenotype.add(displayPheno);
        //  tbGraphVoronoi.add(displayVoronoi);
        //  tbGraphDiscretization.add(displayDiscretization);
        //  tbGraph3D.add(display3DDynamic);
        pop.createRandomPopulation(1, new Default());
        pop.evaluate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPopulation = new javax.swing.JTabbedPane();
        tbTxtGenotype = new javax.swing.JPanel();
        srcollpane = new javax.swing.JScrollPane();
        txtGeno = new javax.swing.JTextArea();
        tbTxtPhenotype = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPheno = new javax.swing.JTextArea();
        tbGraphGenotype = new javax.swing.JPanel();
        tbGraphPhenotype = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbPopulation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbPopulation.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbPopulation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbPopulationStateChanged(evt);
            }
        });
        tbPopulation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbPopulationFocusGained(evt);
            }
        });

        tbTxtGenotype.setLayout(new java.awt.BorderLayout());

        txtGeno.setColumns(20);
        txtGeno.setEditable(false);
        txtGeno.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtGeno.setRows(5);
        srcollpane.setViewportView(txtGeno);

        tbTxtGenotype.add(srcollpane, java.awt.BorderLayout.CENTER);

        tbPopulation.addTab("TXT Genotype", tbTxtGenotype);

        tbTxtPhenotype.setLayout(new java.awt.BorderLayout());

        txtPheno.setColumns(20);
        txtPheno.setEditable(false);
        txtPheno.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtPheno.setRows(5);
        jScrollPane2.setViewportView(txtPheno);

        tbTxtPhenotype.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tbPopulation.addTab("TXT  Phenotype", tbTxtPhenotype);

        tbGraphGenotype.setLayout(new java.awt.BorderLayout());
        tbPopulation.addTab("GR Genotype", tbGraphGenotype);

        tbGraphPhenotype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbGraphPhenotypeFocusGained(evt);
            }
        });
        tbGraphPhenotype.setLayout(new java.awt.BorderLayout());
        tbPopulation.addTab("GR Phenotype", tbGraphPhenotype);

        getContentPane().add(tbPopulation, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPopulationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbPopulationFocusGained
}//GEN-LAST:event_tbPopulationFocusGained

    private void tbPopulationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbPopulationStateChanged
        displayPopulation(pop,solver);
}//GEN-LAST:event_tbPopulationStateChanged

    private void tbGraphPhenotypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbGraphPhenotypeFocusGained
}//GEN-LAST:event_tbGraphPhenotypeFocusGained

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.is_Shown_In_The_Screen = false;
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.is_Shown_In_The_Screen = true;
    }//GEN-LAST:event_formComponentShown

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        this.is_Shown_In_The_Screen = false;
    }//GEN-LAST:event_formWindowIconified

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        this.is_Shown_In_The_Screen = true;
    }//GEN-LAST:event_formWindowDeiconified

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    public  void displayPopulation(Population pop, SimpleSolver solver) {
        //not visible
        if (!is_Shown_In_The_Screen) {
            return;
        }

        if (tbPopulation.getSelectedComponent() == tbTxtGenotype) {
            txtGeno.setText(pop.toSortedStringGenotype());
            txtGeno.setCaretPosition(0);
            return;
        }
        if (tbPopulation.getSelectedComponent() == tbTxtPhenotype) {
            txtPheno.setText(pop.toSortedStringPhenotype());
            txtPheno.setCaretPosition(0);
            return;
        }
        if (tbPopulation.getSelectedComponent() == tbGraphGenotype) {
            
            displayBits.setSolver(solver, pop);
            tbGraphGenotype.repaint();
            return;
        }

        if (tbPopulation.getSelectedComponent() == tbGraphPhenotype) {
            displayPheno.setSolver(solver, pop);
            tbGraphPhenotype.repaint();
            return;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PanelOfPopulation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane srcollpane;
    private javax.swing.JPanel tbGraphGenotype;
    private javax.swing.JPanel tbGraphPhenotype;
    private javax.swing.JTabbedPane tbPopulation;
    private javax.swing.JPanel tbTxtGenotype;
    private javax.swing.JPanel tbTxtPhenotype;
    private javax.swing.JTextArea txtGeno;
    private javax.swing.JTextArea txtPheno;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pop
     */
    public Population getPop() {
        return pop;
    }

    /**
     * @param pop the pop to set
     */
    public void setSolver(SimpleSolver solver, Population pop) {
        if (is_Shown_In_The_Screen) {
            this.solver = solver;
            this.pop = pop.getClone();
        }
    }

    public void setPopulation(Population pop) {
        this.pop = pop;
    }
}
