/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import genetic.Solver.SimpleSolver;
import genetic.Solver.GA;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import utils.SolverContainer;

/**
 *
 * @author ZULU
 */
public class RunSimpleSolver extends javax.swing.JFrame implements Runnable {

    Thread autorun = null;
    boolean running = false;
    //solver and container
    SimpleSolver solver = new GA();
    SolverContainer frmSolver = new SolverContainer(solver, this);
    // population
    PanelOfPopulation displayPopulation = new PanelOfPopulation();
    PanelOfPopulation displaySelect = new PanelOfPopulation();
    //Stats
    PanelOfStatistics displayStats;
    //main meno of this frame
    JFrame mainMenu;
    //frame setup
    SetupSolver setup = null;

    /**
     * Creates new form RunSolver
     */
    public RunSimpleSolver(JFrame mainMenu) {
        initComponents();
        this.mainMenu = mainMenu;

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        displayPopulation.setTitle("Main Population");
        displayPopulation.setBounds(this.getWidth(), 0, dim.width - this.getWidth(), this.getHeight());
        displayPopulation.setSolver(solver, solver.parents);
        displayPopulation.setVisible(true);

        displaySelect.setTitle("Offspring Population");
        displaySelect.setBounds(0, this.getHeight(), this.getWidth(), dim.height - this.getHeight() - 50);
        displaySelect.setSolver(solver, solver.children);
        displaySelect.setVisible(true);

        displayStats = new PanelOfStatistics(solver);
        displayStats.setBounds(this.getWidth(), this.getHeight(), dim.width - this.getWidth(), dim.height - this.getHeight() - 50);
        displayStats.setVisible(true);
        displaySolverEvolution();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btStartStop = new javax.swing.JButton();
        tpInfo = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfoSolver = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSolverEvolution = new javax.swing.JTextArea();
        pbEvolution = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        sldDelay = new javax.swing.JSlider();
        txtDelay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btStartStop1 = new javax.swing.JButton();
        btRestartSolver = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btStartStop2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Run Solver");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
        });

        btStartStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Evolution_64.png"))); // NOI18N
        btStartStop.setText("Start");
        btStartStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStartStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartStopActionPerformed(evt);
            }
        });

        txtInfoSolver.setColumns(20);
        txtInfoSolver.setEditable(false);
        txtInfoSolver.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtInfoSolver.setRows(5);
        jScrollPane1.setViewportView(txtInfoSolver);

        tpInfo.addTab("Solver", new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Dna_24x24.png")), jScrollPane1); // NOI18N

        txtSolverEvolution.setEditable(false);
        txtSolverEvolution.setColumns(20);
        txtSolverEvolution.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtSolverEvolution.setRows(5);
        jScrollPane3.setViewportView(txtSolverEvolution);

        tpInfo.addTab("Evolution", new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Graphic_24x24.png")), jScrollPane3); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 2, 5));

        jLabel22.setText("delay");
        jPanel1.add(jLabel22);

        sldDelay.setMaximum(20);
        sldDelay.setValue(1);
        sldDelay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDelayStateChanged(evt);
            }
        });
        jPanel1.add(sldDelay);

        txtDelay.setText("0");
        jPanel1.add(txtDelay);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/home_64.png"))); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        btStartStop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/setup_small32_icon.png"))); // NOI18N
        btStartStop1.setText("Setup");
        btStartStop1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStartStop1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStartStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartStop1ActionPerformed(evt);
            }
        });
        jPanel2.add(btStartStop1);

        btRestartSolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Restart_32x32.png"))); // NOI18N
        btRestartSolver.setText("Restart ");
        btRestartSolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRestartSolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRestartSolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestartSolverActionPerformed(evt);
            }
        });
        jPanel2.add(btRestartSolver);

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Exit_64.png"))); // NOI18N
        btExit.setText("Exit");
        btExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btStartStop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/step_by_step_64.png"))); // NOI18N
        btStartStop2.setText("Step");
        btStartStop2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStartStop2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStartStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartStop2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbEvolution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btStartStop2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tpInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btStartStop, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btStartStop2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbEvolution, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btExit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartStopActionPerformed
//        tpInfo.setSelectedIndex(1);
//        if (!running) {
//            running = true;
//            autorun = new Thread(this);
//            autorun.start();
//        } 

        tpInfo.setSelectedIndex(1);
        if (autorun == null) {
            running = true;
            autorun = new Thread(this);
            autorun.start();
            btStartStop.setText("Stop");
        } else if (running == false && !solver.isDone()) {
            btStartStop.setText("Stop");
            running = true;
            autorun = new Thread(this);
            autorun.start();
        } else {
            running = false;
        }
    }//GEN-LAST:event_btStartStopActionPerformed

    private void sldDelayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDelayStateChanged
        txtDelay.setText(sldDelay.getValue() * 50 + "");
    }//GEN-LAST:event_sldDelayStateChanged

    private void btStartStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartStop1ActionPerformed
        tpInfo.setSelectedIndex(0);
        //--------------solver container --------------
        frmSolver = new SolverContainer(solver, this);
        //---------------------------------------------
        setup = new SetupSolver(frmSolver);
        setup.setVisible(true);
        displayPopulation.setVisible(false);
        displaySelect.setVisible(false);
        displayStats.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btStartStop1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        //extracted solver from container
        solver = frmSolver.solver;

        displayStats.setSolver(solver);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        displayStats.setBounds(this.getWidth(), this.getHeight(), dim.width - this.getWidth(), dim.height - this.getHeight() - 50);
        tpInfo.setSelectedIndex(0);
        txtInfoSolver.setText(solver.getInfo());
        if (!running) {
            btRestartSolverActionPerformed(null);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btRestartSolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestartSolverActionPerformed
        //stop solver
        if (this.running) {
            running = false;
            autorun = null;
            return;
        }
        solver.restartSolver();
        displayStats.setSolver(solver);
        displayStats.setVisible(true);
        displayPopulation.setVisible(true);
        displaySelect.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        displayStats.setBounds(this.getWidth(), this.getHeight(), dim.width - this.getWidth(), dim.height - this.getHeight() - 50);
        displaySolverEvolution();
    }//GEN-LAST:event_btRestartSolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainMenu.setVisible(true);
        this.dispose();
        displayPopulation.dispose();
        displaySelect.dispose();
        displayStats.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed

        displayPopulation.dispose();
        displaySelect.dispose();
        displayStats.dispose();
        mainMenu.dispose();
        if( setup != null)
            setup.dispose();
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void btStartStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartStop2ActionPerformed
        running = false;
        autorun = null;
        btStartStop.setText("Start");
        solver.iterate();
        displaySolverEvolution();
    }//GEN-LAST:event_btStartStop2ActionPerformed

    public void displaySolverEvolution() {
        txtSolverEvolution.setText(solver.getEvolutionInfo());
        txtSolverEvolution.setCaretPosition(0);
        pbEvolution.setValue((int) (solver.getStop().getProgress() * 100));
        displayPopulation.setSolver(solver, solver.parents);
        displayPopulation.displayPopulation(solver.parents, solver);
        displaySelect.setSolver(solver, solver.children);
        displaySelect.displayPopulation(solver.children, solver);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btRestartSolver;
    private javax.swing.JButton btStartStop;
    private javax.swing.JButton btStartStop1;
    private javax.swing.JButton btStartStop2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JProgressBar pbEvolution;
    private javax.swing.JSlider sldDelay;
    private javax.swing.JTabbedPane tpInfo;
    private javax.swing.JTextField txtDelay;
    private javax.swing.JTextArea txtInfoSolver;
    private javax.swing.JTextArea txtSolverEvolution;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        running = true;
        while (running) {
            solver.iterate();
            displaySolverEvolution();
            if (!running || autorun == null || solver.getStop().isDone(solver)) {
                break;
            }
            try {
                int delay = Integer.parseInt(txtDelay.getText());
                autorun.sleep(delay);
            } catch (InterruptedException ex) {
                Logger.getLogger(RunSimpleSolver.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        running = false;
        btStartStop.setText("Start");
        if (solver.isDone()) {
            autorun = null;
        }

    }
}
